/*The Person class represents a single person that exist within the simulation. Each person should
have at least the following attributes:
 string Id - A person’s unique identifier to assist with debugging and analysis.
 int TravelStartTime – The time of day on a 24-hour clock when this person may start
travelling to other locations.
o Must be less than “TravelEndTime”
 int TravelEndTime – The time of day on a 24-hour clock when this person may stop
travelling to other locations.
o Must be greater than “TravelStartTime”
 bool IsInfected – A Boolean flag to indicate whether a person is currently infected.
 int InfectionCount – An indicator of how many times a person has been infected.
 int InfectionSpreadCount – An indicator of how many times a person has spread the
disease to another person.
 bool IsDead – A Boolean flag to indicate that the person is no longer alive, and therefore
can no longer travel between locations, and can no longer catch or spread the disease.
 bool IsQuarantined – A Boolean flag to indicate whether a person is quarantined,
meaning that they will not travel to other locations and will not spread the disease, but will
resume travel once recovered from the disease.
 double QuarantineChance – A percentage of the likelihood this person is to quarantine
themselves once infected.
o Must be clamped between 0 and 1.
o This should be generated by the configuration file at runtime.
o The configuration file will provide a mean and a standard deviation.
o This value must be randomly generated based on a normal random distribution as
defined by the configuration file.
 */
namespace Project3
{
    public class Person
    {
        public string Id { get; set; }
        public int TravelStartTime { get; set; }
        public int TravelEndTime { get; set; }
        public bool IsInfected { get; set; }
        public int InfectionCount { get; set; }
        public int InfectionSpreadCount { get; set; }
        public bool IsDead { get; set; }
        public bool IsQuarantined { get; set; }
        public double QuarantineChance { get; set; }
    }
}
